### PR TITLE
Adding java version for quick sort in ascending order

### PR DESCRIPTION
**Pull request by afflato**
Adding java version for quick sort in ascending order

### CODE REVIEW

**Comment by Matrix278** [comment]
Hm, there is already quick sort

**Comment by Matrix278** [comment]
Ok, I think name it just as quickSort2 then

**Comment by afflato** [comment]
Took pull from upstream to get updated repository that has QuickSort, Resolved all local conflicts and renamed file to QuickSort2. Thanks

**Comment by Matrix278** [comment]
Good job, thank you for contribution

**Pull request merged**
